In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'sales_data.csv')

In [3]:
df

           date     product     category   price  quantity  revenue
0    2022-01-01  Smartphone  Electronics   600.0      10.0   6000.0
1    2022-01-01      Laptop  Electronics  1200.0       5.0   6000.0
2    2022-01-02     T-Shirt     Clothing    20.0      50.0   1000.0
3    2022-01-03  Headphones  Electronics   100.0      20.0   2000.0
4    2022-01-04     T-Shirt     Clothing    20.0      25.0    500.0
..          ...         ...          ...     ...       ...      ...
364  2022-12-27       Watch  Accessories   150.0       5.0    750.0
365  2022-12-28        Coat     Clothing   100.0       5.0    500.0
366  2022-12-29  Headphones  Electronics   100.0      10.0   1000.0
367  2022-12-30  Smartphone  Electronics   600.0      11.0   6600.0
368  2022-12-31      Hoodie     Clothing    40.0      30.0   1200.0

[369 rows x 6 columns]

In [4]:
df.columns

Index(['date', 'product', 'category', 'price', 'quantity', 'revenue'], dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      369 non-null    object
 1   product   369 non-null    object
 2   category  369 non-null    object
 3   price     367 non-null    float64
 4   quantity  368 non-null    float64
 5   revenue   368 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.4+ KB

In [6]:
df.isnull().sum()

date        0
product     0
category    0
price       2
quantity    1
revenue     1
dtype: int64

In [7]:
df.describe()

             price    quantity      revenue
count   367.000000  368.000000   368.000000
mean    211.226158   14.565217  2060.679348
std     227.335170    8.595740  1910.930790
min      20.000000    3.000000   300.000000
25%      50.000000    8.000000   800.000000
50%     100.000000   12.000000  1200.000000
75%     300.000000   20.000000  2400.000000
max    1200.000000   50.000000  7200.000000

In [8]:
df.dropna(inplace=True)

In [9]:
df.isna().sum()

date        0
product     0
category    0
price       0
quantity    0
revenue     0
dtype: int64

In [11]:
df.duplicated().sum()

1

In [13]:
df.drop_duplicates(inplace = True)

In [15]:
df.duplicated().sum()

0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 364 entries, 0 to 368
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      364 non-null    object
 1   product   364 non-null    object
 2   category  364 non-null    object
 3   price     364 non-null    float64
 4   quantity  364 non-null    float64
 5   revenue   364 non-null    float64
dtypes: float64(3), object(3)
memory usage: 19.9+ KB

In [16]:
df

           date     product     category   price  quantity  revenue
0    2022-01-01  Smartphone  Electronics   600.0      10.0   6000.0
1    2022-01-01      Laptop  Electronics  1200.0       5.0   6000.0
2    2022-01-02     T-Shirt     Clothing    20.0      50.0   1000.0
3    2022-01-03  Headphones  Electronics   100.0      20.0   2000.0
4    2022-01-04     T-Shirt     Clothing    20.0      25.0    500.0
..          ...         ...          ...     ...       ...      ...
364  2022-12-27       Watch  Accessories   150.0       5.0    750.0
365  2022-12-28        Coat     Clothing   100.0       5.0    500.0
366  2022-12-29  Headphones  Electronics   100.0      10.0   1000.0
367  2022-12-30  Smartphone  Electronics   600.0      11.0   6600.0
368  2022-12-31      Hoodie     Clothing    40.0      30.0   1200.0

[364 rows x 6 columns]

In [17]:
df.to_csv(r'D:\Desktop\cleaned sales_data.csv')